name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Lua interpreter
        uses: leafo/gh-actions-lua@v11

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up Purescript and spago
        run: |
          npm i -g purescript
          npm i -g spago@next

      - name: Download pslua
        run: wget -c https://github.com/Unisay/purescript-lua/releases/download/0.2/pslua-linux_x86_64.tar.gz -O - | tar -xz

      - run: mkdir bin
      - run: mv pslua bin

      - name: Put pslua on PATH
        run: realpath bin >> $GITHUB_PATH

      - name: Build without testing because there aren't any tests
        run: spago build
